name: "test"

on:
  repository_dispatch:
    types: [update]


jobs:
  update-manifest:
    runs-on: ubuntu-latest
    timeout-minutes: 300

    steps:
      - uses: actions/checkout@v2

      - name: Sample
        run: |
          echo ${{ github.event.client_payload.sha }}
          echo ${{ github.event.client_payload.env }}

